name: 'deploy'

on:
  push:
    branches:
      - master
      - dokku
      - "dokku**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push to dokku
        uses: dokku/github-action@v1.4.0
        with:
          # specify `--force` as a flag for git pushes
          git_push_flags: '--force'
          git_remote_url: 'ssh://dokku@c.iphoting.cc:3022/munin'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
